# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    image: mongo

  portainer:
    container_name: portainer
    image: portainer/portainer-ce

  basketdb:
    container_name: basketdb
    image: redis:alpine

  discountdb:
    container_name: discountdb
    image: postgres

  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4

  catalog.api:
    container_name: catalog.api
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    container_name: basket.api
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    container_name: discount.api
    image: discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    container_name: discount.grpc
    image: discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile

  ordering.api:
    container_name: ordering.api
    image: orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: